import EsriDESConfigInterface from 'types/ESRIConfig';

const EsriDESConfig: EsriDESConfigInterface = {
  PortalToken: process.env.PORTAL_API_KEY || '',
  WebMap: '270a1c95409f406c9b046398519bbc94',
  FeatureLayers: {
    sites: {
      QueryOutputFields: [],
      url: 'https://services1.arcgis.com/HrMiNYsSqqPpLTDE/ArcGIS/rest/services/Site_Public_Staging/FeatureServer/0',
      UniqueColumnName: 'Datum',
      YearsRangeColumnName: null,
      DateColumnName: null,
      AnalyteColumnName: null,
      QueryOrderFields: [],
    },
    regions: {
      QueryOutputFields: ['NRM_Region'],
      url: 'https://services1.arcgis.com/HrMiNYsSqqPpLTDE/ArcGIS/rest/services/Regions_Public_Staging/FeatureServer/0',
      UniqueColumnName: 'NRM_Region',
      YearsRangeColumnName: null,
      DateColumnName: null,
      AnalyteColumnName: null,
      QueryOrderFields: [],
    },
    basins: {
      QueryOutputFields: ['RepReg', 'NRM_Region'],
      url: 'https://services1.arcgis.com/HrMiNYsSqqPpLTDE/ArcGIS/rest/services/Basins_Public_Staging/FeatureServer/0',
      UniqueColumnName: 'RepReg',
      YearsRangeColumnName: null,
      DateColumnName: null,
      AnalyteColumnName: null,
      QueryOrderFields: [],
    },
  },
  Tables: {
    Analytes: {
      QueryOutputFields: [],
      url: 'https://services1.arcgis.com/HrMiNYsSqqPpLTDE/ArcGIS/rest/services/Analytes_Public_Staging/FeatureServer/0',
      UniqueColumnName: 'primary_analyte_group',
      YearsRangeColumnName: null,
      DateColumnName: null,
      AnalyteColumnName: null,
      QueryOrderFields: [],
    },
    AnnualLoad: {
      QueryOutputFields: [],
      url: 'https://services1.arcgis.com/HrMiNYsSqqPpLTDE/ArcGIS/rest/services/Annual_Load_Yield_Report_Public_Staging/FeatureServer/0',
      UniqueColumnName: 'Number_of_Samples',
      YearsRangeColumnName: 'Date__YYYY_YYYY_',
      DateColumnName: null,
      AnalyteColumnName: 'Analyte',
      QueryOrderFields: [
        'Region',
        'Basin',
        'Site_Code',
        'Date__YYYY_YYYY_',
        'Analyte',
      ],
    },
    AnnualFlow: {
      QueryOutputFields: [],
      url: 'https://services1.arcgis.com/HrMiNYsSqqPpLTDE/ArcGIS/rest/services/Annual_Flow_Public_Staging/FeatureServer/0',
      UniqueColumnName: 'Flow_Cumecs',
      YearsRangeColumnName: 'Date__YYYY_YYYY_',
      DateColumnName: 'Date_Time',
      AnalyteColumnName: null,
      QueryOrderFields: ['Site_Code', 'Date__YYYY_YYYY_', 'Date_Time'],
    },
    AnnualConcentration: {
      QueryOutputFields: [],
      url: 'https://services1.arcgis.com/HrMiNYsSqqPpLTDE/ArcGIS/rest/services/Annual_Concentration_Public_Staging/FeatureServer/0',
      UniqueColumnName: 'Value__mg_per_L_',
      YearsRangeColumnName: 'Date__YYYY_YYYY_',
      DateColumnName: 'Date_Time',
      AnalyteColumnName: 'Analyte',
      QueryOrderFields: [
        'Site_Code',
        'Analyte',
        'Date__YYYY_YYYY_',
        'Date_Time',
      ],
    },
    DailyLoad: {
      QueryOutputFields: [],
      url: 'https://services1.arcgis.com/HrMiNYsSqqPpLTDE/ArcGIS/rest/services/Daily_Load_Report_Public_Staging/FeatureServer/0',
      UniqueColumnName: 'Calculation_Method',
      YearsRangeColumnName: 'Date__YYYY_YYYY_',
      DateColumnName: 'Date',
      AnalyteColumnName: 'Analyte',
      QueryOrderFields: [
        'Region',
        'Basin',
        'Site_Code',
        'Date__YYYY_YYYY_',
        'Date',
        'Analyte',
      ],
    },

    PRMDaily: {
      QueryOutputFields: [],
      url: 'https://services1.arcgis.com/HrMiNYsSqqPpLTDE/ArcGIS/rest/services/PRM_Daily_Report_Public_Staging/FeatureServer/0',
      UniqueColumnName: 'Status',
      YearsRangeColumnName: 'Date__YYYY_YYYY_',
      DateColumnName: 'Date',
      AnalyteColumnName: null,
      QueryOrderFields: [
        'Region',
        'Basin',
        'Site_Code',
        'Date__YYYY_YYYY_',
        'Date',
      ],
    },

    PRMWetSeason: {
      QueryOutputFields: [],
      url: 'https://services1.arcgis.com/HrMiNYsSqqPpLTDE/ArcGIS/rest/services/PRM_WetSeason_Report_Public_Staging/FeatureServer/0',
      UniqueColumnName: 'Status',
      YearsRangeColumnName: 'Date__YYYY_YYYY_',
      DateColumnName: null,
      AnalyteColumnName: null,
      QueryOrderFields: ['Region', 'Basin', 'Site_Code', 'Date__YYYY_YYYY_'],
    },

    Concentration: {
      QueryOutputFields: [],
      url: 'https://services1.arcgis.com/HrMiNYsSqqPpLTDE/ArcGIS/rest/services/Concentration_Report_Public_Staging/FeatureServer/0',
      UniqueColumnName: 'Collection_Method',
      YearsRangeColumnName: 'Date__YYYY_YYYY_',
      DateColumnName: 'Date_Time',
      AnalyteColumnName: 'Analyte',
      QueryOrderFields: [
        'Region',
        'Basin',
        'Site_Code',
        'Date__YYYY_YYYY_',
        'Date_Time',
        'Analyte',
      ],
    },

    AnalytesOrder: {
      QueryOutputFields: [],
      url: 'https://services1.arcgis.com/HrMiNYsSqqPpLTDE/ArcGIS/rest/services/Analytes_Order_Public_Staging/FeatureServer/0',
      UniqueColumnName: 'analyte_order',
      YearsRangeColumnName: null,
      DateColumnName: null,
      AnalyteColumnName: null,
      QueryOrderFields: [],
    },
  },
  DatePickerOptions: {
    Everything: 10,
    YearsRange: 20,
    DateRange: 30,
  },
  RegionsOrderField: 'Reg_Order',
  AnalytesOrderField: 'analyte_order',
  UniqueAnalyteGroup: 'Pesticides for Pesticides Risk Metric',
  QueryParamsAll: `/query?f=pjson&outFields=*&returnGeometry=false&returnIdsOnly=false&where=1%3D1`,
  QueryParamsNoWhere: `/query?f=pjson&outFields=*&returnGeometry=false&returnIdsOnly=false`,
  QueryInternalSitesOIDs: `/query?f=pjson&outFields=*&returnGeometry=false&returnIdsOnly=true&where=Site_Owner+like+%27%25WQI%25%27`,
  DownloadLimit: 500000,
};

export default EsriDESConfig;
